/*
* generated by Xtext
*/
package iit.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class KinDslStandaloneSetup extends KinDslStandaloneSetupGenerated{

	public static void doSetup() {
		new KinDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

