/*
 * generated by Xtext
 */
package iit.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KinDslRuntimeModule extends iit.dsl.AbstractKinDslRuntimeModule {

}
